"use client";

import Link from "next/link";
import { Building2, Check, CircleAlert, FileCheck2, ShieldCheck, Stethoscope, X } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useAdminSession } from "../../admin-shell";
import { ConfirmDialog, EmptyState, LoadingSkeleton, PageHeader, StatusBadge, Tabs, useToast } from "../../admin-ui";
import type { Clinic, ClinicLocation, Doctor, DoctorAssociation } from "../../admin-types";

type DoctorTab = "summary" | "documents" | "assignments";

export function DoctorDetailPage({ doctorId, tab = "summary" }: { doctorId: string; tab?: DoctorTab }) {
  const { apiRequest, can } = useAdminSession(); const { showToast } = useToast(); const [doctor, setDoctor] = useState<Doctor | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [confirm, setConfirm] = useState<null | "approve" | "reject" | "suspend" | "reactivate">(null); const [reason, setReason] = useState("");
  const load = useCallback(async () => { setLoading(true); try { setDoctor(await apiRequest<Doctor>(`/v1/admin/doctors/${doctorId}`)); setError(""); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Unable to load doctor"); } finally { setLoading(false); } }, [apiRequest, doctorId]); useEffect(() => { void load(); }, [load]);
  const base = `/admin/doctors/${doctorId}`; const tabs = [{ href: base, label: "Summary" }, { href: `${base}/documents`, label: "Documents" }, { href: `${base}/clinic-assignments`, label: "Clinic assignments" }]; const active = tab === "summary" ? base : tab === "documents" ? `${base}/documents` : `${base}/clinic-assignments`;
  const readiness = useMemo(() => { if (!doctor) return []; const approvedDocuments = doctor.documents?.filter((document) => document.platformStatus === "APPROVED").length ?? 0; return [{ label: "Platform account approved", ready: doctor.status === "APPROVED", reason: doctor.status === "APPROVED" ? "Identity decision complete" : `Account status is ${doctor.status.toLowerCase().replaceAll("_", " ")}` }, { label: "Verification document approved", ready: approvedDocuments > 0, reason: approvedDocuments ? `${approvedDocuments} approved document${approvedDocuments > 1 ? "s" : ""}` : "No platform-approved document is available" }, { label: "Specialty configured", ready: Boolean(doctor.specialties?.length), reason: doctor.specialties?.length ? doctor.specialties.map((item) => item.specialty.name).join(", ") : "Add at least one specialty" }, { label: "Clinic assignment approved", ready: Boolean(doctor.clinicAssociations?.some((association) => association.status === "APPROVED")), reason: doctor.clinicAssociations?.some((association) => association.status === "APPROVED") ? "Approved clinic association found" : "Assign the doctor to an active clinic location" }]; }, [doctor]);
  async function runAction() { if (!confirm) return; setBusy(true); try { const body = confirm === "reject" ? { reason: reason || "Information needs correction" } : confirm === "suspend" ? { reason: reason || undefined } : {}; await apiRequest(`/v1/admin/doctors/${doctorId}/${confirm}`, { method: "POST", body: JSON.stringify(body) }); showToast(`Doctor ${confirm} action completed`); setConfirm(null); setReason(""); await load(); } catch (actionError) { setError(actionError instanceof Error ? actionError.message : "Unable to update doctor"); } finally { setBusy(false); } }
  if (loading) return <><PageHeader title="Doctor details" description="Loading provider record…" /><LoadingSkeleton rows={7} /></>;
  if (!doctor) return <><PageHeader title="Doctor unavailable" description="The requested provider record could not be loaded." />{error && <div className="admin-v2-alert error">{error}</div>}<EmptyState title="Doctor unavailable" description="Return to the directory to select another doctor." action={<Link className="primary-button" href="/admin/doctors">Doctor directory</Link>} /></>;
  const allReady = readiness.every((item) => item.ready);
  return <><PageHeader eyebrow="Provider record" title={doctor.user.fullName} description={`${doctor.licenseNumber || "License not recorded"} · ${doctor.user.email || "No email"}`} actions={<><StatusBadge status={doctor.status} />{can("doctor.manage") && doctor.status === "PENDING_APPROVAL" && <><button className="primary-button" onClick={() => setConfirm("approve")} type="button">Approve</button><button className="danger-button" onClick={() => setConfirm("reject")} type="button">Reject</button></>}{can("doctor.manage") && doctor.status === "APPROVED" && <button onClick={() => setConfirm("suspend")} type="button">Suspend</button>}{can("doctor.manage") && (doctor.status === "SUSPENDED" || doctor.status === "REJECTED") && <button className="primary-button" onClick={() => setConfirm("reactivate")} type="button">Reactivate</button>}</>} /><Tabs active={active} items={tabs} />{error && <div className="admin-v2-alert error">{error}</div>}
    {tab === "summary" && <div className="admin-v2-detail-grid"><section className="admin-v2-card"><div className="admin-v2-doctor-profile"><span className="admin-v2-avatar admin-v2-avatar-lg">{doctor.user.fullName.split(" ").map((part) => part[0]).slice(0, 2).join("")}</span><div><h2>{doctor.user.fullName}</h2><p>{doctor.qualifications || "Qualifications not provided"}</p></div></div><dl className="admin-v2-details"><div><dt>License</dt><dd>{doctor.licenseNumber || "Not recorded"}</dd></div><div><dt>Experience</dt><dd>{doctor.yearsExperience === null ? "Not recorded" : `${doctor.yearsExperience} years`}</dd></div><div><dt>Specialties</dt><dd>{doctor.specialties?.map((item) => item.specialty.name).join(", ") || "Not configured"}</dd></div><div><dt>Languages</dt><dd>{doctor.languages?.join(", ") || "Not configured"}</dd></div><div className="span-2"><dt>Biography</dt><dd>{doctor.bio || "No professional biography has been added."}</dd></div></dl></section><section className="admin-v2-card"><div className="admin-v2-card-header"><div><h2>Public listing and booking readiness</h2><p>{allReady ? "Core listing checks are complete." : "Resolve the items below before public availability."}</p></div>{allReady ? <ShieldCheck className="success" size={22} /> : <CircleAlert className="warning" size={22} />}</div><div className="admin-v2-readiness">{readiness.map((item) => <div className={item.ready ? "ready" : "blocked"} key={item.label}>{item.ready ? <Check size={17} /> : <X size={17} />}<span><strong>{item.label}</strong><small>{item.reason}</small></span></div>)}</div><div className="admin-v2-readiness-note"><Stethoscope size={17} /><p><strong>Service and availability readiness</strong> also require an active doctor service and generated slots. These are clinic-assignment-specific and are managed after the association is approved.</p></div></section></div>}
    {tab === "documents" && <section className="admin-v2-card"><div className="admin-v2-card-header"><div><h2>Documents and verification</h2><p>Identity and professional documents submitted by the doctor.</p></div><FileCheck2 size={20} /></div><div className="admin-v2-record-list">{doctor.documents?.map((document) => <article key={document.id}><span className="admin-v2-avatar"><FileCheck2 size={17} /></span><div><strong>{document.file.originalFilename}</strong><p>{document.documentType.replaceAll("_", " ")} · {document.file.mimeType}</p><small>{document.file.visibility} visibility</small></div><StatusBadge status={document.platformStatus} /></article>)}{!doctor.documents?.length && <EmptyState title="No documents submitted" description="The doctor has not uploaded any verification documents." />}</div><div className="admin-v2-info-note">Platform document verification is read-only here because the current backend exposes clinic-level document review but no platform document verification endpoint.</div></section>}
    {tab === "assignments" && <DoctorAssignments doctor={doctor} />}
    <ConfirmDialog busy={busy} confirmLabel={confirm ? `${confirm.charAt(0).toUpperCase()}${confirm.slice(1)} doctor` : "Confirm"} danger={confirm === "reject" || confirm === "suspend"} description={confirm === "approve" ? "Approval confirms the platform identity decision. Public booking still depends on clinic, service, and availability readiness." : `This will ${confirm ?? "update"} the provider account. Existing clinical records remain preserved.`} onCancel={() => { setConfirm(null); setReason(""); }} onConfirm={() => void runAction()} open={Boolean(confirm)} title={`${confirm ? confirm.charAt(0).toUpperCase() + confirm.slice(1) : "Update"} ${doctor.user.fullName}?`} />
  </>;
}

function DoctorAssignments({ doctor }: { doctor: Doctor }) {
  const { apiRequest } = useAdminSession(); const { showToast } = useToast(); const [clinics, setClinics] = useState<Clinic[]>([]); const [clinicId, setClinicId] = useState(""); const [locations, setLocations] = useState<ClinicLocation[]>([]); const [locationId, setLocationId] = useState(""); const [associations, setAssociations] = useState<DoctorAssociation[]>(doctor.clinicAssociations ?? []); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { void apiRequest<{ clinics: Clinic[] }>("/v1/admin/clinics").then((result) => { setClinics(result.clinics); setClinicId(result.clinics[0]?.id ?? ""); }).catch(() => setClinics([])); }, [apiRequest]);
  useEffect(() => { if (!clinicId) return; void Promise.all([apiRequest<{ locations: ClinicLocation[] }>(`/v1/clinics/${clinicId}/locations`), apiRequest<{ associations: DoctorAssociation[] }>(`/v1/clinics/${clinicId}/doctor-associations`)]).then(([locationResult, associationResult]) => { setLocations(locationResult.locations); setLocationId(locationResult.locations[0]?.id ?? ""); setAssociations(associationResult.associations.filter((association) => association.doctor?.id === doctor.id || (association.doctor as Doctor | undefined)?.id === doctor.id)); }).catch(() => { setLocations([]); setAssociations([]); }); }, [apiRequest, clinicId, doctor.id]);
  async function assign() { setBusy(true); setError(""); try { await apiRequest(`/v1/clinics/${clinicId}/doctor-associations`, { method: "POST", body: JSON.stringify({ doctorId: doctor.id, clinicLocationId: locationId, currency: "LKR", defaultSlotIntervalMinutes: 15, bufferMinutes: 0 }) }); showToast("Doctor assigned to clinic"); const result = await apiRequest<{ associations: DoctorAssociation[] }>(`/v1/clinics/${clinicId}/doctor-associations`); setAssociations(result.associations.filter((association) => association.doctor?.id === doctor.id)); } catch (assignError) { setError(assignError instanceof Error ? assignError.message : "Unable to assign doctor"); } finally { setBusy(false); } }
  return <div className="admin-v2-detail-grid"><section className="admin-v2-card"><div className="admin-v2-card-header"><div><h2>Clinic assignments</h2><p>Approved and pending associations for the selected clinic.</p></div><Building2 size={20} /></div><label className="admin-v2-location-select"><span>Clinic</span><select onChange={(e) => setClinicId(e.target.value)} value={clinicId}>{clinics.map((clinic) => <option key={clinic.id} value={clinic.id}>{clinic.name}</option>)}</select></label><div className="admin-v2-record-list">{associations.map((association) => <article key={association.id}><span className="admin-v2-avatar"><Building2 size={17} /></span><div><strong>{association.clinic.name}</strong><p>{association.clinicLocation.name || association.clinicLocation.address}</p></div><StatusBadge status={association.status} /></article>)}{!associations.length && <EmptyState title="No assignment at this clinic" description="Assign the doctor to one of the clinic’s active locations." />}</div></section><section className="admin-v2-card admin-v2-form-section"><div className="admin-v2-card-header"><div><h2>Assign to location</h2><p>Creates an approved association using the existing admin workflow.</p></div></div><label>Clinic<select onChange={(e) => setClinicId(e.target.value)} value={clinicId}>{clinics.map((clinic) => <option key={clinic.id} value={clinic.id}>{clinic.name}</option>)}</select></label><label>Location<select onChange={(e) => setLocationId(e.target.value)} value={locationId}>{locations.map((location) => <option key={location.id} value={location.id}>{location.name || location.address}</option>)}</select></label>{error && <div className="admin-v2-alert error">{error}</div>}<button className="primary-button" disabled={busy || !clinicId || !locationId || doctor.status !== "APPROVED"} onClick={() => void assign()} type="button">{doctor.status !== "APPROVED" ? "Approve doctor before assigning" : busy ? "Assigning…" : "Assign doctor"}</button></section></div>;
}
