"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, Stethoscope } from "lucide-react";
import { useEffect, useState, type FormEvent } from "react";
import { useAdminSession } from "../admin-shell";
import { FormSection, PageHeader, useToast } from "../admin-ui";
import type { Specialty } from "../admin-types";

export function DoctorCreatePage() {
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const { apiRequest, apiUrl } = useAdminSession(); const { showToast } = useToast(); const router = useRouter(); const [specialties, setSpecialties] = useState<Specialty[]>([]); const [form, setForm] = useState({ email: "", phone: "", fullName: "", password: "", licenseNumber: "", qualifications: "", bio: "", yearsExperience: "", languages: "English", specialtyIds: [] as string[] }); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { void fetch(`${apiUrl}/v1/specialties`).then(async (response) => response.ok ? response.json() as Promise<{ specialties: Specialty[] }> : Promise.reject(new Error("Unable to load specialties"))).then((result) => setSpecialties(result.specialties)).catch(() => setSpecialties([])); }, [apiUrl]);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { await fetch(`${apiUrl}/v1/auth/register/doctor`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: form.email, phone: form.phone || undefined, fullName: form.fullName, password: form.password, licenseNumber: form.licenseNumber, qualifications: form.qualifications || null, bio: form.bio || null, yearsExperience: form.yearsExperience ? Number(form.yearsExperience) : null, languages: form.languages.split(",").map((value) => value.trim()).filter(Boolean), specialtyIds: form.specialtyIds }) }).then(async (response) => { if (!response.ok) { const payload = await response.json().catch(() => null) as { message?: string }; throw new Error(payload?.message || "Unable to register doctor"); } }); showToast("Doctor registered and added to the approval queue"); router.push("/admin/doctors/pending"); } catch (submitError) { setError(submitError instanceof Error ? submitError.message : "Unable to register doctor"); } finally { setBusy(false); } }
  return <><PageHeader eyebrow="Provider network" title="Register doctor" description="Create a pending doctor account. The doctor must complete email verification and pass platform review before approval." actions={<Link className="admin-v2-secondary-button" href="/admin/doctors"><ArrowLeft size={17} />Back to doctors</Link>} /><form className="admin-v2-form-layout" onSubmit={submit}><FormSection title="Account information" description="Credentials are delivered securely; passwords are never shown after submission."><div className="admin-v2-form-grid"><label>Full name<input autoFocus onChange={(e) => setForm({ ...form, fullName: e.target.value })} required value={form.fullName} /></label><label>Email address<input onChange={(e) => setForm({ ...form, email: e.target.value })} required type="email" value={form.email} /></label><label>Phone number<input onChange={(e) => setForm({ ...form, phone: e.target.value })} value={form.phone} /></label><label>Temporary password<input autoComplete="new-password" minLength={8} onChange={(e) => setForm({ ...form, password: e.target.value })} required type="password" value={form.password} /><small>Minimum 8 characters. Share it outside this portal using an approved channel.</small></label></div></FormSection><FormSection title="Professional profile"><div className="admin-v2-form-grid"><label>License number<input onChange={(e) => setForm({ ...form, licenseNumber: e.target.value })} required value={form.licenseNumber} /></label><label>Years of experience<input min="0" onChange={(e) => setForm({ ...form, yearsExperience: e.target.value })} type="number" value={form.yearsExperience} /></label><label>Qualifications<input onChange={(e) => setForm({ ...form, qualifications: e.target.value })} value={form.qualifications} /></label><label>Languages<input onChange={(e) => setForm({ ...form, languages: e.target.value })} value={form.languages} /><small>Comma-separated.</small></label><label className="span-2">Specialties<select multiple onChange={(e) => setForm({ ...form, specialtyIds: Array.from(e.target.selectedOptions, (option) => option.value) })} value={form.specialtyIds}>{specialties.map((specialty) => <option key={specialty.id} value={specialty.id}>{specialty.name}</option>)}</select></label><label className="span-2">Professional biography<textarea onChange={(e) => setForm({ ...form, bio: e.target.value })} value={form.bio} /></label></div></FormSection>{error && <div className="admin-v2-alert error">{error}</div>}<div className="admin-v2-form-footer"><Link href="/admin/doctors">Cancel</Link><button className="primary-button" disabled={busy} type="submit"><Stethoscope size={17} />{busy ? "Registering…" : "Register doctor"}</button></div></form></>;
}
