"use client";

import Link from "next/link";
import { Plus, Search } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useAdminSession } from "../admin-shell";
import { DataTable, EmptyState, FilterBar, LoadingSkeleton, PageHeader, Pagination, StatusBadge, usePaginatedItems } from "../admin-ui";
import { type Doctor, type DoctorStatus } from "../admin-types";

const statuses: Array<DoctorStatus | "ALL"> = ["ALL", "PENDING_APPROVAL", "APPROVED", "REJECTED", "SUSPENDED"];

export function DoctorListPage({ pendingOnly = false, title = "Doctor directory", description = "Search provider records, review verification status, and inspect operational readiness." }: { pendingOnly?: boolean; title?: string; description?: string }) {
  const { apiRequest, can } = useAdminSession(); const [doctors, setDoctors] = useState<Doctor[]>([]); const [query, setQuery] = useState(""); const [status, setStatus] = useState<DoctorStatus | "ALL">(pendingOnly ? "PENDING_APPROVAL" : "ALL"); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { setLoading(true); void apiRequest<{ doctors: Doctor[] }>("/v1/admin/doctors").then((result) => setDoctors(result.doctors)).catch((loadError) => setError(loadError instanceof Error ? loadError.message : "Unable to load doctors")).finally(() => setLoading(false)); }, [apiRequest]);
  const filtered = useMemo(() => doctors.filter((doctor) => { const term = query.trim().toLowerCase(); return (status === "ALL" || doctor.status === status) && (!term || doctor.user.fullName.toLowerCase().includes(term) || doctor.user.email?.toLowerCase().includes(term) || doctor.licenseNumber?.toLowerCase().includes(term)); }), [doctors, query, status]); const visible = usePaginatedItems(filtered, page, 10);
  useEffect(() => setPage(1), [query, status]);
  return <><PageHeader eyebrow="Provider network" title={title} description={description} actions={can("doctor.manage") ? <Link className="primary-button" href="/admin/doctors/new"><Plus size={17} />Register doctor</Link> : undefined} /><section className="admin-v2-card admin-v2-table-card"><FilterBar><label className="admin-v2-search-field"><span className="sr-only">Search doctors</span><Search size={17} /><input onChange={(e) => setQuery(e.target.value)} placeholder="Search by doctor, email, or license" value={query} /></label><label><span>Status</span><select onChange={(e) => setStatus(e.target.value as DoctorStatus | "ALL")} value={status}>{statuses.map((value) => <option key={value} value={value}>{value === "ALL" ? "All statuses" : value.replaceAll("_", " ")}</option>)}</select></label></FilterBar>{error && <div className="admin-v2-alert error">{error}</div>}{loading ? <LoadingSkeleton /> : visible.length ? <><DataTable label="Doctors"><thead><tr><th>Doctor</th><th>Status</th><th>Specialty</th><th>License</th><th>Documents</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{visible.map((doctor) => <tr key={doctor.id}><td><div className="admin-v2-entity"><span className="admin-v2-avatar admin-v2-avatar-text">{doctor.user.fullName.split(" ").map((part) => part[0]).slice(0, 2).join("")}</span><span><strong>{doctor.user.fullName}</strong><small>{doctor.user.email || doctor.slug}</small></span></div></td><td><StatusBadge status={doctor.status} /></td><td>{doctor.specialties?.map((item) => item.specialty.name).join(", ") || "Not set"}</td><td>{doctor.licenseNumber || "Pending"}</td><td>{doctor.documents?.length ?? 0}</td><td><Link className="admin-v2-table-action" href={`/admin/doctors/${doctor.id}`}>Review</Link></td></tr>)}</tbody></DataTable><Pagination onPageChange={setPage} page={page} pageSize={10} total={filtered.length} /></> : <EmptyState title="No doctors found" description={query || status !== "ALL" ? "Adjust the search or status filter." : "Provider records will appear after registration."} />}</section></>;
}
