"use client";

import { CalendarDays, RefreshCcw } from "lucide-react";
import { useState, type FormEvent } from "react";
import { useAdminSession } from "./admin-shell";
import { FormSection, PageHeader, StatusBadge, useToast } from "./admin-ui";

export function SlotAdminPage() {
  const { apiRequest } = useAdminSession(); const { showToast } = useToast(); const today = new Date().toISOString().slice(0, 10); const nextMonth = new Date(Date.now() + 30 * 86400000).toISOString().slice(0, 10); const [form, setForm] = useState({ doctorClinicId: "", fromDate: today, toDate: nextMonth }); const [job, setJob] = useState<{ id?: string; jobId?: string; status?: string } | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const result = await apiRequest<{ id?: string; jobId?: string; status?: string }>("/v1/admin/slots/regenerate", { method: "POST", body: JSON.stringify({ doctorClinicId: form.doctorClinicId || undefined, fromDate: form.fromDate, toDate: form.toDate, reason: "manual" }) }); setJob(result); showToast("Slot regeneration queued"); } catch (submitError) { setError(submitError instanceof Error ? submitError.message : "Unable to queue slot regeneration"); } finally { setBusy(false); } }
  return <><PageHeader eyebrow="Scheduling" title="Generated slots" description="Queue an audited regeneration job for all approved associations or one doctor-clinic assignment." /><div className="admin-v2-detail-grid"><form onSubmit={submit}><FormSection title="Regenerate appointment slots" description="Existing bookings are preserved. Slot generation follows current hours, availability, breaks, time off, closures, and services."><div className="admin-v2-form-grid"><label className="span-2">Doctor-clinic association ID <small>Optional. Leave blank to regenerate all approved associations.</small><input onChange={(e) => setForm({ ...form, doctorClinicId: e.target.value })} value={form.doctorClinicId} /></label><label>From date<input onChange={(e) => setForm({ ...form, fromDate: e.target.value })} required type="date" value={form.fromDate} /></label><label>To date<input min={form.fromDate} onChange={(e) => setForm({ ...form, toDate: e.target.value })} required type="date" value={form.toDate} /></label></div>{error && <div className="admin-v2-alert error">{error}</div>}<div className="admin-v2-section-actions"><button className="primary-button" disabled={busy} type="submit"><RefreshCcw size={16} />{busy ? "Queueing…" : "Queue regeneration"}</button></div></FormSection></form><section className="admin-v2-card admin-v2-job-card"><span className="admin-v2-brand-mark"><CalendarDays size={22} /></span><h2>Latest job</h2>{job ? <><StatusBadge status={job.status || "QUEUED"} /><dl><div><dt>Job ID</dt><dd>{job.jobId || job.id || "Queued by worker"}</dd></div><div><dt>Scope</dt><dd>{form.doctorClinicId || "All approved associations"}</dd></div><div><dt>Date range</dt><dd>{form.fromDate} to {form.toDate}</dd></div></dl></> : <p>No regeneration job has been queued in this session.</p>}</section></div></>;
}
